### ISSUE TITLE
Getting a error in colab- TypeError: unsupported operand type(s) for /: 'NoneType' and 'float

### ISSUE THREAD

**Issue by AkTheBoss001** [compphoto/BoostYourOwnDepth#4] opened 2023-03-06 10:38 UTC

**Comment by sebastian-dille** [comment] 2023-03-06 18:35
Hi @AkTheBoss001, this looks like either the weights or one of the images are not loaded properly. Can you please tell me which section is producing the error?

**Comment by AkTheBoss001** [comment] 2023-03-07 00:43
> Hi @AkTheBoss001, this looks like either the weights or one of the images are not loaded properly. Can you please tell me which section is producing the error?

In code section 3

**Comment by oscarqht** [comment] 2023-03-07 08:19
I'm having the same issue on section 3, I think it is caused by wrong file path:

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/165961/223365782-6f3cb00c-ac5e-4cc5-9c2a-51f0b9d6cea2.png">

The full code block output:

```
device: cuda
Namespace(checkpoints_dir='/content/BoostYourOwnDepth/pix2pix/checkpoints', colorize_results=True, data_dir='/content/BoostYourOwnDepth/input/', max_res=inf, output_dir='/content/BoostYourOwnDepth/output', output_resolution=1, pix2pixsize=1024)
----------------- Options ---------------
                    Final: False                         
                       R0: False                         
                      R20: False                         
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: /content/BoostYourOwnDepth/pix2pix/checkpoints	[default: ./pix2pix/checkpoints]
         colorize_results: True                          	[default: False]
                crop_size: 672                           
                 data_dir: /content/BoostYourOwnDepth/input/	[default: None]
                 dataroot: None                          
             dataset_mode: depthmerge                    
                 depthNet: None                          
                direction: AtoB                          
          display_winsize: 256                           
                    epoch: latest                        
                     eval: False                         
            generatevideo: None                          
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 2                             
                  isTrain: False                         	[default: None]
                load_iter: 0                             	[default: 0]
                load_size: 672                           
         max_dataset_size: 10000                         
                  max_res: inf                           
                    model: pix2pix4depth                 
               n_layers_D: 3                             
                     name: void                          
                      ndf: 64                            
                     netD: basic                         
                     netG: unet_1024                     
 net_receptive_field_size: None                          
                      ngf: 64                            
               no_dropout: False                         
                  no_flip: False                         
                     norm: none                          
                 num_test: 50                            
              num_threads: 4                             
               output_dir: /content/BoostYourOwnDepth/output	[default: None]
                output_nc: 1                             
        output_resolution: None                          
                    phase: test                          
              pix2pixsize: None                          
               preprocess: resize_and_crop               
                savecrops: None                          
             savewholeest: None                          
           serial_batches: False                         
                   suffix:                               
                  verbose: False                         
----------------- End -------------------
initialize network with normal
loading the model from /content/BoostYourOwnDepth/pix2pix/checkpoints/mergemodel/latest_net_G.pth
start processing
[ WARN:0@3.869] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/content/BoostYourOwnDepth/input/high-res/1-384.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/content/BoostYourOwnDepth/boost_depth.py", line 146, in <module>
    run(dataset_, option_)
  File "/content/BoostYourOwnDepth/boost_depth.py", line 54, in run
    for image_ind, images in enumerate(dataset):
  File "/content/BoostYourOwnDepth/utils.py", line 194, in __getitem__
    return Depths(self.lr_depth_dir,self.hr_depth_dir, self.files, index)
  File "/content/BoostYourOwnDepth/utils.py", line 175, in __init__
    self.high_res = read_image(os.path.join(hr_dir, name))
  File "/content/BoostYourOwnDepth/utils.py", line 26, in read_image
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)/255.0
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

**Comment by oscarqht** [comment] 2023-03-07 08:50
The source code assume image file to have the same name under `high-res` and `low-res` input folders, but this is not stated in the colab notebook. Simply renaming the files to the same name can fix this issue. It would be great if @sebastian-dille could add related requirement in the notebook to prevent others bump into the same issue :)

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/165961/223370619-2d73912c-7814-48f2-b344-3555786e6bb3.png">

**Comment by oscarqht** [comment] 2023-03-07 08:51
@AkTheBoss001 Please also provide your notebook output, so that we can confirm whether we're having the same issue :)

**Comment by sebastian-dille** [comment] 2023-03-07 17:51
Hi @m0o0scar, thanks for the feedback. Yes, the filenames should match. I've added a note to the description.
@AkTheBoss001 Please let me know if the error on your side still persists and if so, please add the output of the notebook, as m0o0scar suggested. I'll have a look into it and hope to get things fixed as soon as possible.

**Comment by sebastian-dille** [comment] 2023-03-29 04:25
closing this issue now

**Closed as completed by sebastian-dille** 2023-03-29 04:25 UTC
